# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — German."""

PRIVACY_ROUTE = {
    "metaTitle": "Datenschutzerklärung | REPUTEXA",
    "metaDescription": "Datenschutzerklärung und Schutz personenbezogener Daten bei REPUTEXA. DSGVO-Konformität, Google-Bewertungen, Stripe-Zahlungen.",
    "pageTitle": "Datenschutzerklärung",
    "intro": "Stand: März 2026. Diese Erklärung beschreibt, wie REPUTEXA Ihre personenbezogenen Daten gemäß der Datenschutz-Grundverordnung (DSGVO) erhebt, nutzt und schützt.",
    "toc1": "1. Verantwortlicher",
    "toc2": "2. Erhobene Daten",
    "toc3": "3. Zwecke und Rechtsgrundlagen",
    "toc4": "4. Google-Bewertungen und API-Zugriff",
    "toc5": "5. Verarbeitung durch künstliche Intelligenz",
    "toc6": "6. Zahlungen und Rechnungsdaten",
    "toc7": "7. Auftragsverarbeiter und Datenübermittlung",
    "toc8": "8. Cookies",
    "toc9": "9. Speicherdauer",
    "toc10": "10. Ihre Rechte",
    "toc11": "11. Sicherheit",
    "toc12": "12. Änderungen",
    "toc13": "13. Kontakt",
    "s1_p1": "Verantwortlicher für die Verarbeitung Ihrer personenbezogenen Daten ist REPUTEXA, Betreiber der Website <b>reputexa.fr</b>, mit Sitz in Frankreich.",
    "s1_p2": "Wir verarbeiten Ihre Daten rechtmäßig, nach Treu und Glauben und transparent gemäß der DSGVO.",
    "s2_intro": "Wir erheben insbesondere:",
    "s2_li1": "<b>E-Mail:</b> geschäftliche E-Mail-Adresse für Kontoerstellung, Kommunikation und Authentifizierung",
    "s2_li2": "<b>Rechnungsdaten:</b> Identität, Kontaktdaten und Zahlungsinformationen, die an Stripe zur Abwicklung von Abonnements und zur Rechnungsstellung übermittelt werden",
    "s2_li3": "<b>Zugriff auf Bewertungen über die Google-API:</b> Inhalt der Bewertungen, Sterne, Daten Ihres Google-Business-Profils (siehe Abschnitt 4)",
    "s2_li4": "<b>Identifikations- und berufliche Daten:</b> Vor- und Nachname, Telefon, Unternehmensname, Adresse, Google Location ID",
    "s2_li5": "<b>Technische Daten:</b> IP-Adresse, Verbindungsprotokolle, Cookies (siehe Abschnitt 8)",
    "s3_intro": "Die Daten werden für die folgenden Zwecke und auf der angegebenen Rechtsgrundlage verarbeitet:",
    "s3_li1": "<b>Vertragserfüllung:</b> Kontoerstellung, Zugang zum Dienst, Abonnementverwaltung",
    "s3_li2": "<b>Berechtigtes Interesse:</b> Serviceverbesserung, interne Analysen, Betrugsprävention",
    "s3_li3": "<b>Einwilligung:</b> Newsletter, Marketing (jederzeit widerrufbar)",
    "s3_li4": "<b>Rechtliche Verpflichtung:</b> Aufbewahrung von Rechnungen, steuerliche Compliance",
    "s4_p1": "Daten zu Google-Bewertungen werden über die Google-Business-Profile-API nach Ihrer Autorisierung erhoben. Dazu gehören der Bewertungstext, die Sterne, das Datum, der Name oder das Pseudonym des Autors und die Kennung Ihres Standorts. Diese Daten dienen der Anzeige im Dashboard, der Erstellung von KI-Antwortvorschlägen (siehe Abschnitt 5), Benachrichtigungen und Reporting.",
    "s4_p2": "<b>Eigentum an den Daten:</b> Die auf dem Google-Business-Profile angezeigten Bewertungsdaten bleiben Eigentum des Kunden oder von Google, je nach Fall. REPUTEXA erhebt keinen Eigentumsanspruch an diesen Inhalten. REPUTEXA ist jedoch berechtigt, sie ausschließlich zur Erbringung des Dienstes und zu den hier beschriebenen Zwecken zu verarbeiten, zu speichern und zu nutzen.",
    "s5_p1": "Erhobene Bewertungen werden durch KI-Modelle (Anbieter wie OpenAI, Google oder gleichwertige) verarbeitet, um personalisierte Antwortvorschläge zu erzeugen — ausschließlich im Auftrag des Nutzers und im Rahmen des REPUTEXA-Dienstes.",
    "s5_p2": "<b>REPUTEXA verkauft, teilt oder monetarisiert Bewertungsdaten oder KI-verarbeitete Inhalte nicht</b> zu anderen Zwecken als der Dienstleistungserbringung. Die KI verarbeitet Bewertungen nur, damit der Kunde antworten und seine Online-Reputation verbessern kann; es erfolgt keine sekundäre Nutzung (zielgerichtete Werbung, Weiterverkauf von Daten, Profiling durch Dritte).",
    "s6_body": "Rechnungs- und Zahlungsdaten werden an <strong>Stripe</strong> (Stripe, Inc.), einen PCI-DSS-zertifizierten Anbieter, zur Abwicklung von Abonnements (Pläne Vision, Pulse, Zenith), Kartentokenisierung und Rechnungsstellung übermittelt. Sensible Kartendaten passieren niemals unsere Server. Stripe-Richtlinie: <stripeLink>stripe.com/de/privacy</stripeLink>.",
    "s7_intro": "Ihre Daten können an die nachstehenden Auftragsverarbeiter übermittelt und dort verarbeitet werden, ausschließlich im Rahmen der jeweiligen Aufgabe. Diese Übermittlungen erfolgen gemäß DSGVO und den Datenschutzrichtlinien der jeweiligen Anbieter:",
    "s7_li1": "<b>Stripe</b> – Zahlungen, Abrechnung und Abonnementverwaltung (Karten, anteilige Abrechnung, Guthaben)",
    "s7_li2": "<b>Resend</b> – Versand transaktionaler E-Mails (Bestätigungen, Warnungen, Kontobenachrichtigungen)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Benachrichtigungen und Warnungen (negative Bewertungen, Erinnerungen), wenn Sie diese Option in Ihrem Tarif aktiviert haben",
    "s7_li4": "<b>Supabase</b> – Hosting von Daten (Datenbank, Authentifizierung); Daten können je nach Konfiguration in der EU gehostet werden",
    "s7_li5": "<b>OpenAI / KI-Anbieter</b> – Verarbeitung von Bewertungen zur Erstellung von Antwortvorschlägen (siehe Abschnitt 5)",
    "s7_li6": "<b>Google</b> – OAuth-Anmeldung und Google-Business-Profile-API (Bewertungen, Einträge)",
    "s7_li7": "<b>Vercel</b> – Hosting der Website und der Anwendung",
    "s7_footer": "Diese Anbieter unterliegen vertraglichen Pflichten im Einklang mit der DSGVO. Die jeweiligen Datenschutzerklärungen (Stripe, Resend, Meta/WhatsApp, Supabase usw.) finden Sie auf den offiziellen Websites.",
    "s8_p1": "Die Website verwendet <b>technisch unbedingt erforderliche Cookies</b> für den Betrieb des Dienstes:",
    "s8_li1": "<b>Sitzung und Authentifizierung</b>: Aufrechterhaltung der Benutzersitzung und Zugriffssicherheit",
    "s8_li2": "<b>Stripe-Sicherheit</b>: für Zahlungsabwicklung und Betrugsprävention erforderliche Cookies",
    "s8_p2": "Für diese Cookies ist keine vorherige Einwilligung im Sinne von Art. 82 des französischen Datenschutzgesetzes und der DSGVO erforderlich, sofern sie für die Diensterbringung unbedingt notwendig sind. Für diese technischen Cookies wird kein separates Einwilligungsbanner angezeigt.",
    "s9_p1": "Ihre Daten werden für die Dauer Ihres Kontos und anschließend für gesetzliche Aufbewahrungsfristen gespeichert (Rechnungen: 10 Jahre). Verbindungsdaten und Protokolle werden höchstens 12 Monate aufbewahrt. Bei Kontolöschung werden Ihre Daten innerhalb von 30 Tagen gelöscht oder anonymisiert, sofern keine gesetzliche Aufbewahrungspflicht entgegensteht.",
    "s10_intro": "Gemäß der DSGVO stehen Ihnen folgende Rechte zu:",
    "s10_li1": "<b>Auskunftsrecht</b> und Recht auf Berichtigung Ihrer Daten",
    "s10_li2": "<b>Recht auf Löschung</b> („Recht auf Vergessenwerden“) innerhalb der gesetzlichen Grenzen",
    "s10_li3": "<b>Recht auf Einschränkung</b> der Verarbeitung",
    "s10_li4": "<b>Recht auf Datenübertragbarkeit</b>",
    "s10_li5": "<b>Widerspruchsrecht</b> gegen die Verarbeitung, insbesondere bei Direktwerbung",
    "s10_rights": "Zur Ausübung dieser Rechte kontaktieren Sie uns unter <contactLink>contact@reputexa.fr</contactLink>. Sie können auch eine Beschwerde bei einer Aufsichtsbehörde einreichen (in Frankreich: CNIL — <cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "Wir setzen angemessene technische und organisatorische Maßnahmen ein (SSL-Verschlüsselung, sichere Authentifizierung, Zugriffskontrollen), um Ihre Daten vor unbefugtem Zugriff, Verlust oder Veränderung zu schützen.",
    "s12_p1": "Wir behalten uns vor, diese Erklärung zu ändern. Wesentliche Änderungen teilen wir per E-Mail oder über eine Mitteilung in Ihrem Kundenbereich mit. Das Datum der letzten Aktualisierung steht am Anfang des Dokuments.",
    "s13_body": "Bei Fragen zum Schutz Ihrer Daten: <contactLink>contact@reputexa.fr</contactLink>.",
}
