# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — English (US)."""

PRIVACY_ROUTE = {
    "metaTitle": "Privacy Policy | REPUTEXA",
    "metaDescription": "REPUTEXA privacy policy and personal data protection. GDPR compliance, Google reviews management, Stripe payments.",
    "pageTitle": "Privacy Policy",
    "intro": "Last updated: March 2026. This policy explains how REPUTEXA collects, uses, and protects your personal data in accordance with the General Data Protection Regulation (GDPR).",
    "toc1": "1. Data controller",
    "toc2": "2. Data we collect",
    "toc3": "3. Purposes and legal bases",
    "toc4": "4. Google reviews and API access",
    "toc5": "5. Artificial intelligence processing",
    "toc6": "6. Payments and billing data",
    "toc7": "7. Subprocessors and data transfers",
    "toc8": "8. Cookies",
    "toc9": "9. Retention period",
    "toc10": "10. Your rights",
    "toc11": "11. Security",
    "toc12": "12. Changes",
    "toc13": "13. Contact us",
    "s1_p1": "The controller of your personal data is REPUTEXA, publisher of the site <b>reputexa.fr</b>, with its registered office in France.",
    "s1_p2": "We process your data lawfully, fairly, and transparently, in accordance with the GDPR.",
    "s2_intro": "We collect in particular:",
    "s2_li1": "<b>Email:</b> professional email address for account creation, communications, and authentication",
    "s2_li2": "<b>Billing data:</b> identity, contact details, and payment information transmitted to Stripe for subscription processing and invoicing",
    "s2_li3": "<b>Google reviews via the Google API:</b> review content, ratings, dates, and data from your Google Business Profile listing (see section 4)",
    "s2_li4": "<b>Identification and professional data:</b> first and last name, phone, business name, address, Google Location ID",
    "s2_li5": "<b>Technical data:</b> IP address, connection logs, cookies (see section 8)",
    "s3_intro": "Data is processed for the following purposes, on the legal bases indicated:",
    "s3_li1": "<b>Performance of a contract:</b> account creation, access to the service, subscription management",
    "s3_li2": "<b>Legitimate interest:</b> service improvement, internal analytics, fraud prevention",
    "s3_li3": "<b>Consent:</b> newsletter and marketing communications (withdrawable at any time)",
    "s3_li4": "<b>Legal obligation:</b> invoice retention, tax compliance",
    "s4_p1": "Google review data is collected through the Google Business Profile API after you grant authorization. This includes review content (text, rating, date), the contributor’s name or display name, and your establishment identifier. This data is used for display in the dashboard, AI-generated reply suggestions (see section 5), alerts, and reporting.",
    "s4_p2": "<b>Ownership of data:</b> Review data displayed on Google Business Profile remains the property of the customer or Google, as applicable. REPUTEXA claims no ownership of this content. REPUTEXA is nonetheless authorized to process, store, and use it strictly to deliver the service and for the purposes described herein.",
    "s5_p1": "Collected reviews are processed by artificial intelligence models (providers such as OpenAI, Google, or equivalents) to generate personalized reply suggestions, solely on behalf of the user and strictly within the scope of the REPUTEXA service.",
    "s5_p2": "<b>REPUTEXA does not sell, share, or monetize review data or AI-processed content</b> for any purpose other than providing the service. AI processes reviews only so the customer can reply to reviews and improve their online reputation; no secondary use (targeted advertising, resale of data, third-party profiling) is performed.",
    "s6_body": "Billing and payment data is transmitted to <strong>Stripe</strong> (Stripe, Inc.), a PCI-DSS certified provider, for subscription processing (Vision, Pulse, Zenith plans), card tokenization, and invoicing. Sensitive card data never passes through our servers. Stripe policy: <stripeLink>stripe.com/privacy</stripeLink>.",
    "s7_intro": "Your data may be transferred to and processed by the subprocessors below, strictly for their assigned role. Such transfers comply with the GDPR and each provider’s privacy policy:",
    "s7_li1": "<b>Stripe</b> – Payments, billing, and subscription management (cards, proration, credits)",
    "s7_li2": "<b>Resend</b> – Transactional email delivery (confirmations, alerts, account notifications)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Notifications and alerts (negative reviews, reminders) when you enable this option on your plan",
    "s7_li4": "<b>Supabase</b> – Data hosting (database, authentication); data may be hosted in the European Union depending on configuration",
    "s7_li5": "<b>OpenAI / AI providers</b> – Review processing for reply suggestions (see section 5)",
    "s7_li6": "<b>Google</b> – OAuth sign-in and Google Business Profile API (reviews, establishment listings)",
    "s7_li7": "<b>Vercel</b> – Hosting of the website and application",
    "s7_footer": "These providers are bound by contractual obligations consistent with the GDPR. You may review their respective privacy policies (Stripe, Resend, Meta/WhatsApp, Supabase, etc.) on their official websites.",
    "s8_p1": "The site uses <b>strictly necessary technical cookies</b> required for the service to operate:",
    "s8_li1": "<b>Session and authentication</b>: maintaining the user session and securing access",
    "s8_li2": "<b>Stripe security</b>: cookies required for payment processing and fraud prevention",
    "s8_p2": "These cookies do not require prior consent under Article 82 of the French Data Protection Act and the GDPR, provided they are strictly necessary to deliver the service. No separate consent banner is shown for these technical cookies.",
    "s9_p1": "Your data is retained for the lifetime of your account, then for applicable statutory periods (invoicing: 10 years). Connection data and logs are kept for up to 12 months. If you delete your account, your data is erased or anonymized within 30 days, unless a legal retention obligation applies.",
    "s10_intro": "Under the GDPR, you have the following rights:",
    "s10_li1": "<b>Right of access</b> and rectification of your data",
    "s10_li2": "<b>Right to erasure</b> (“right to be forgotten”) within the limits set by law",
    "s10_li3": "<b>Right to restriction</b> of processing",
    "s10_li4": "<b>Right to data portability</b>",
    "s10_li5": "<b>Right to object</b> to processing, including for prospecting",
    "s10_rights": "To exercise these rights, contact us at <contactLink>contact@reputexa.fr</contactLink>. You may also lodge a complaint with a supervisory authority (in France, the CNIL: <cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "We implement appropriate technical and organizational measures (SSL encryption, secure authentication, access controls) to protect your data against unauthorized access, loss, or alteration.",
    "s12_p1": "We may update this policy. Any material change will be communicated by email or through a notification in your customer area. The last update date is shown at the top of this document.",
    "s13_body": "For any questions about how we protect your data: <contactLink>contact@reputexa.fr</contactLink>.",
}
