# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — Spanish."""

PRIVACY_ROUTE = {
    "metaTitle": "Política de privacidad | REPUTEXA",
    "metaDescription": "Política de privacidad y protección de datos personales de REPUTEXA. Cumplimiento del RGPD, reseñas de Google, pagos con Stripe.",
    "pageTitle": "Política de privacidad",
    "intro": "Última actualización: marzo de 2026. Esta política describe cómo REPUTEXA recopila, utiliza y protege sus datos personales de conformidad con el Reglamento General de Protección de Datos (RGPD).",
    "toc1": "1. Responsable del tratamiento",
    "toc2": "2. Datos que recopilamos",
    "toc3": "3. Finalidades y bases legales",
    "toc4": "4. Reseñas de Google y acceso API",
    "toc5": "5. Tratamiento mediante inteligencia artificial",
    "toc6": "6. Pagos y datos de facturación",
    "toc7": "7. Subencargados y transferencias de datos",
    "toc8": "8. Cookies",
    "toc9": "9. Plazo de conservación",
    "toc10": "10. Sus derechos",
    "toc11": "11. Seguridad",
    "toc12": "12. Modificaciones",
    "toc13": "13. Contacto",
    "s1_p1": "El responsable del tratamiento de sus datos personales es REPUTEXA, editor del sitio <b>reputexa.fr</b>, con domicilio social en Francia.",
    "s1_p2": "Tratamos sus datos de forma lícita, leal y transparente, de conformidad con el RGPD.",
    "s2_intro": "Recopilamos en particular:",
    "s2_li1": "<b>Correo electrónico:</b> dirección profesional para la creación de la cuenta, las comunicaciones y la autenticación",
    "s2_li2": "<b>Datos de facturación:</b> identidad, datos de contacto e información de pago transmitida a Stripe para la gestión de suscripciones y la emisión de facturas",
    "s2_li3": "<b>Acceso a reseñas vía API de Google:</b> contenido de las reseñas, valoraciones, fechas y datos de su ficha de Google Business Profile (véase la sección 4)",
    "s2_li4": "<b>Datos de identificación y profesionales:</b> nombre, apellidos, teléfono, nombre del establecimiento, dirección, Google Location ID",
    "s2_li5": "<b>Datos técnicos:</b> dirección IP, registros de conexión, cookies (véase la sección 8)",
    "s3_intro": "Los datos se tratan con las siguientes finalidades, sobre las bases jurídicas indicadas:",
    "s3_li1": "<b>Ejecución del contrato:</b> creación de la cuenta, acceso al servicio, gestión de la suscripción",
    "s3_li2": "<b>Interés legítimo:</b> mejora del servicio, analítica interna, prevención del fraude",
    "s3_li3": "<b>Consentimiento:</b> boletín y comunicaciones comerciales (revocable en cualquier momento)",
    "s3_li4": "<b>Obligación legal:</b> conservación de facturas, cumplimiento fiscal",
    "s4_p1": "Los datos relativos a las reseñas de Google se recopilan a través de la API de Google Business Profile tras su autorización. Incluyen el contenido de las reseñas (texto, valoración, fecha), el nombre o seudónimo del autor y el identificador de su establecimiento. Estos datos se utilizan para mostrarlos en el panel, generar sugerencias de respuesta mediante IA (véase la sección 5), alertas e informes.",
    "s4_p2": "<b>Propiedad de los datos:</b> Los datos de reseñas mostrados en Google Business Profile siguen siendo propiedad del cliente o de Google, según el caso. REPUTEXA no reclama ningún derecho de propiedad sobre dichos contenidos. REPUTEXA está autorizada a tratarlos, almacenarlos y utilizarlos estrictamente para prestar el servicio y para las finalidades descritas en el presente documento.",
    "s5_p1": "Las reseñas recopiladas son tratadas por modelos de inteligencia artificial (proveedores como OpenAI, Google u otros equivalentes) para generar sugerencias de respuesta personalizadas, exclusivamente en nombre del usuario y en el marco estricto del servicio REPUTEXA.",
    "s5_p2": "<b>REPUTEXA no vende, comparte ni monetiza los datos de reseñas ni el contenido tratado por la IA</b> con fines distintos a la prestación del servicio. La IA trata las reseñas únicamente para permitir al cliente responder a sus reseñas y mejorar su reputación online; no se realiza ningún uso secundario (publicidad dirigida, reventa de datos, elaboración de perfiles por terceros).",
    "s6_body": "Los datos de facturación y pago se transmiten a <strong>Stripe</strong> (Stripe, Inc.), proveedor certificado PCI-DSS, para el tratamiento de suscripciones (planes Vision, Pulse, Zenith), la tokenización de tarjetas y la emisión de facturas. Los datos bancarios sensibles nunca pasan por nuestros servidores. Política de Stripe: <stripeLink>stripe.com/privacy</stripeLink>.",
    "s7_intro": "Sus datos pueden ser transferidos y tratados por los subencargados que figuran a continuación, estrictamente en el marco de su misión. Estas transferencias se realizan de conformidad con el RGPD y las políticas de privacidad de cada proveedor:",
    "s7_li1": "<b>Stripe</b> – Pagos, facturación y gestión de suscripciones (tarjetas, prorrateo, créditos)",
    "s7_li2": "<b>Resend</b> – Envío de correos transaccionales (confirmación, alertas, notificaciones de cuenta)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Envío de notificaciones y alertas (reseñas negativas, recordatorios) cuando active esta opción en su plan",
    "s7_li4": "<b>Supabase</b> – Alojamiento de datos (base de datos, autenticación); los datos pueden alojarse en la Unión Europea según la configuración",
    "s7_li5": "<b>OpenAI / proveedores de IA</b> – Tratamiento de reseñas para generar sugerencias de respuesta (véase la sección 5)",
    "s7_li6": "<b>Google</b> – Inicio de sesión OAuth y API de Google Business Profile (reseñas, fichas de establecimiento)",
    "s7_li7": "<b>Vercel</b> – Alojamiento del sitio web y de la aplicación",
    "s7_footer": "Estos proveedores están sujetos a obligaciones contractuales conformes al RGPD. Puede consultar sus respectivas políticas de privacidad (Stripe, Resend, Meta/WhatsApp, Supabase, etc.) en sus sitios oficiales.",
    "s8_p1": "El sitio utiliza <b>cookies técnicas estrictamente necesarias</b> para el funcionamiento del servicio:",
    "s8_li1": "<b>Sesión y autenticación</b>: mantenimiento de la sesión del usuario y seguridad del acceso",
    "s8_li2": "<b>Seguridad de Stripe</b>: cookies necesarias para el tratamiento de pagos y la prevención del fraude",
    "s8_p2": "Estas cookies no requieren consentimiento previo en el sentido del artículo 82 de la ley « Informática y libertades » y del RGPD, siempre que sean estrictamente necesarias para prestar el servicio. No se muestra ningún banner de consentimiento específico para estas cookies técnicas.",
    "s9_p1": "Sus datos se conservan durante la vigencia de su cuenta y, a continuación, durante los plazos legales aplicables (facturación: 10 años). Los datos de conexión y registros se conservan como máximo 12 meses. En caso de eliminación de la cuenta, sus datos se suprimen o anonimizan en un plazo de 30 días, salvo obligación legal de conservación.",
    "s10_intro": "De conformidad con el RGPD, usted dispone de los siguientes derechos:",
    "s10_li1": "<b>Derecho de acceso</b> y rectificación de sus datos",
    "s10_li2": "<b>Derecho de supresión</b> (« derecho al olvido ») dentro de los límites previstos por la ley",
    "s10_li3": "<b>Derecho a la limitación</b> del tratamiento",
    "s10_li4": "<b>Derecho a la portabilidad</b> de los datos",
    "s10_li5": "<b>Derecho de oposición</b> al tratamiento, en particular con fines de prospección",
    "s10_rights": "Para ejercer estos derechos, contáctenos en <contactLink>contact@reputexa.fr</contactLink>. También puede presentar una reclamación ante la autoridad de control (en Francia, la CNIL: <cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "Implementamos medidas técnicas y organizativas adecuadas (cifrado SSL, autenticación segura, control de accesos) para proteger sus datos frente a accesos no autorizados, pérdida o alteración.",
    "s12_p1": "Nos reservamos el derecho de modificar esta política. Cualquier modificación sustancial se comunicará por correo electrónico o mediante una notificación en su área de cliente. La fecha de la última actualización figura al inicio del documento.",
    "s13_body": "Para cualquier cuestión relativa a la protección de sus datos: <contactLink>contact@reputexa.fr</contactLink>.",
}
