# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — French (source legal text)."""

PRIVACY_ROUTE = {
    "metaTitle": "Politique de confidentialité | REPUTEXA",
    "metaDescription": "Politique de confidentialité et protection des données personnelles de REPUTEXA. Conformité RGPD, gestion des avis Google, paiements Stripe.",
    "pageTitle": "Politique de confidentialité",
    "intro": "Dernière mise à jour : mars 2026. Cette politique définit comment REPUTEXA collecte, utilise et protège vos données personnelles conformément au Règlement général sur la protection des données (RGPD).",
    "toc1": "1. Responsable du traitement",
    "toc2": "2. Données collectées",
    "toc3": "3. Finalités et bases légales",
    "toc4": "4. Avis Google et accès API",
    "toc5": "5. Traitement par intelligence artificielle",
    "toc6": "6. Paiements et données de facturation",
    "toc7": "7. Sous-traitants et transfert de données",
    "toc8": "8. Cookies",
    "toc9": "9. Durée de conservation",
    "toc10": "10. Vos droits",
    "toc11": "11. Sécurité",
    "toc12": "12. Modifications",
    "toc13": "13. Nous contacter",
    "s1_p1": "Le responsable du traitement des données personnelles est REPUTEXA, éditeur du site <b>reputexa.fr</b>, dont le siège est établi en France.",
    "s1_p2": "Nous traitons vos données de manière licite, loyale et transparente, conformément au RGPD.",
    "s2_intro": "Nous collectons notamment :",
    "s2_li1": "<b>Email :</b> adresse email professionnelle pour la création du compte, les communications et l'authentification",
    "s2_li2": "<b>Données de facturation :</b> identité, coordonnées et informations de paiement transmises à Stripe pour le traitement des abonnements et la délivrance des factures",
    "s2_li3": "<b>Accès aux avis via l'API Google :</b> contenu des avis, notes, dates, données de votre fiche Google Business Profile (cf. section 4)",
    "s2_li4": "<b>Données d'identification et professionnelles :</b> nom, prénom, téléphone, nom de l'établissement, adresse, Google Location ID",
    "s2_li5": "<b>Données techniques :</b> adresse IP, logs de connexion, cookies (cf. section 8)",
    "s3_intro": "Les données sont traitées pour les finalités suivantes, sur les bases juridiques indiquées :",
    "s3_li1": "<b>Exécution du contrat :</b> création du compte, accès au service, gestion de l'abonnement",
    "s3_li2": "<b>Intérêt légitime :</b> amélioration du service, analytics internes, prévention des fraudes",
    "s3_li3": "<b>Consentement :</b> newsletter, communications marketing (révocable à tout moment)",
    "s3_li4": "<b>Obligation légale :</b> conservation des factures, conformité fiscale",
    "s4_p1": "Les données relatives aux avis Google sont collectées via l'API Google Business Profile après votre autorisation. Il s'agit notamment du contenu des avis (texte, note, date), du nom ou pseudo du contributeur et de l'identifiant de votre établissement. Ces données servent à l'affichage dans le dashboard, à la génération de suggestions de réponses par IA (voir section 5), aux alertes et au reporting.",
    "s4_p2": "<b>Propriété des données :</b> Les données d'avis affichées sur Google Business Profile restent la propriété du client ou de Google, selon le cas. REPUTEXA ne revendique aucune propriété sur ces contenus. REPUTEXA est toutefois habilitée à les traiter, les stocker et les utiliser dans le cadre strict de la fourniture du service et des finalités décrites aux présentes.",
    "s5_p1": "Les avis collectés sont traités par des modèles d'intelligence artificielle (fournisseurs tels que OpenAI, Google ou équivalents) afin de générer des suggestions de réponses personnalisées, pour le compte exclusif de l'utilisateur et dans le cadre strict de la prestation REPUTEXA.",
    "s5_p2": "<b>REPUTEXA ne revend, ne partage ni ne monétise les données d'avis ou les contenus traités par l'IA</b> à des fins autres que la fourniture du service. L'IA traite les avis uniquement pour permettre au client de répondre à ses avis et d'améliorer sa e-réputation ; aucun usage secondaire (publicité ciblée, revente de données, profilage tiers) n'est effectué.",
    "s6_body": "Les données de facturation et de paiement sont transmises à <strong>Stripe</strong> (Stripe, Inc.), prestataire certifié PCI-DSS, pour le traitement des abonnements (plans Vision, Pulse, Zenith), la tokenisation des cartes bancaires et la délivrance des factures. Les données bancaires sensibles ne transitent jamais par nos serveurs. Politique Stripe : <stripeLink>stripe.com/fr/privacy</stripeLink>.",
    "s7_intro": "Vos données peuvent être transférées et traitées par les sous-traitants ci-après, dans le strict cadre de leur mission. Ces transferts sont effectués conformément au RGPD et aux politiques de confidentialité propres à chaque prestataire :",
    "s7_li1": "<b>Stripe</b> – Paiements, facturation et gestion des abonnements (cartes, prorata, crédits)",
    "s7_li2": "<b>Resend</b> – Envoi d'emails transactionnels (confirmation, alertes, notifications de compte)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Envoi de notifications et alertes (avis négatifs, rappels) lorsque vous avez activé cette option sur votre plan",
    "s7_li4": "<b>Supabase</b> – Hébergement des données (base de données, authentification) ; les données peuvent être hébergées dans l'Union européenne selon la configuration",
    "s7_li5": "<b>OpenAI / fournisseurs d'IA</b> – Traitement des avis pour la génération de suggestions de réponses (cf. section 5)",
    "s7_li6": "<b>Google</b> – Connexion OAuth et API Google Business Profile (avis, fiches établissement)",
    "s7_li7": "<b>Vercel</b> – Hébergement du site et de l'application",
    "s7_footer": "Ces prestataires sont soumis à des obligations contractuelles conformes au RGPD. Vous pouvez consulter leurs politiques de confidentialité respectives (Stripe, Resend, Meta/WhatsApp, Supabase, etc.) sur leurs sites officiels.",
    "s8_p1": "Le site utilise des <b>cookies techniques strictement indispensables</b> au fonctionnement du service :",
    "s8_li1": "<b>Session et authentification</b> : maintien de la session utilisateur et sécurité de l'accès",
    "s8_li2": "<b>Sécurité Stripe</b> : cookies nécessaires au traitement des paiements et à la prévention des fraudes",
    "s8_p2": "Ces cookies ne requièrent pas de consentement préalable au sens de l'article 82 de la loi « Informatique et Libertés » et du RGPD, dès lors qu'ils sont strictement nécessaires à la fourniture du service. Aucun bandeau de consentement spécifique n'est affiché pour ces cookies techniques.",
    "s9_p1": "Vos données sont conservées pendant la durée de votre compte, puis pendant les délais légaux applicables (facturation : 10 ans). Les données de connexion et logs sont conservés au maximum 12 mois. En cas de suppression de compte, vos données sont supprimées ou anonymisées dans un délai de 30 jours, sauf obligation de conservation légale.",
    "s10_intro": "Conformément au RGPD, vous disposez des droits suivants :",
    "s10_li1": "<b>Droit d'accès</b> et de rectification de vos données",
    "s10_li2": "<b>Droit à l'effacement</b> (« droit à l'oubli ») dans les limites prévues par la loi",
    "s10_li3": "<b>Droit à la limitation</b> du traitement",
    "s10_li4": "<b>Droit à la portabilité</b> des données",
    "s10_li5": "<b>Droit d'opposition</b> au traitement, notamment pour la prospection",
    "s10_rights": "Pour exercer ces droits, contactez-nous à <contactLink>contact@reputexa.fr</contactLink>. Vous pouvez également introduire une réclamation auprès de la CNIL (<cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "Nous mettons en œuvre des mesures techniques et organisationnelles appropriées (chiffrement SSL, authentification sécurisée, contrôle d'accès) pour protéger vos données contre tout accès non autorisé, perte ou altération.",
    "s12_p1": "Nous nous réservons le droit de modifier cette politique. Toute modification significative sera communiquée par email ou via une notification dans votre espace client. La date de dernière mise à jour est indiquée en tête du document.",
    "s13_body": "Pour toute question relative à la protection de vos données : <contactLink>contact@reputexa.fr</contactLink>.",
}
