# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — Italian."""

PRIVACY_ROUTE = {
    "metaTitle": "Informativa sulla privacy | REPUTEXA",
    "metaDescription": "Informativa sulla privacy e protezione dei dati personali di REPUTEXA. Conformità GDPR, recensioni Google, pagamenti Stripe.",
    "pageTitle": "Informativa sulla privacy",
    "intro": "Ultimo aggiornamento: marzo 2026. La presente informativa descrive come REPUTEXA raccoglie, utilizza e protegge i suoi dati personali in conformità al Regolamento generale sulla protezione dei dati (GDPR).",
    "toc1": "1. Titolare del trattamento",
    "toc2": "2. Dati raccolti",
    "toc3": "3. Finalità e basi giuridiche",
    "toc4": "4. Recensioni Google e accesso API",
    "toc5": "5. Trattamento tramite intelligenza artificiale",
    "toc6": "6. Pagamenti e dati di fatturazione",
    "toc7": "7. Responsabili del trattamento e trasferimenti",
    "toc8": "8. Cookie",
    "toc9": "9. Conservazione",
    "toc10": "10. I suoi diritti",
    "toc11": "11. Sicurezza",
    "toc12": "12. Modifiche",
    "toc13": "13. Contatti",
    "s1_p1": "Il titolare del trattamento dei dati personali è REPUTEXA, editore del sito <b>reputexa.fr</b>, con sede in Francia.",
    "s1_p2": "Trattiamo i suoi dati in modo leale, lecito e trasparente, in conformità al GDPR.",
    "s2_intro": "Raccogliamo in particolare:",
    "s2_li1": "<b>Email:</b> indirizzo email professionale per la creazione dell'account, le comunicazioni e l'autenticazione",
    "s2_li2": "<b>Dati di fatturazione:</b> identità, recapiti e informazioni di pagamento trasmesse a Stripe per la gestione degli abbonamenti e l'emissione delle fatture",
    "s2_li3": "<b>Accesso alle recensioni tramite API Google:</b> contenuto delle recensioni, valutazioni, date e dati della scheda Google Business Profile (cfr. sezione 4)",
    "s2_li4": "<b>Dati identificativi e professionali:</b> nome, cognome, telefono, nome della struttura, indirizzo, Google Location ID",
    "s2_li5": "<b>Dati tecnici:</b> indirizzo IP, log di connessione, cookie (cfr. sezione 8)",
    "s3_intro": "I dati sono trattati per le finalità seguenti, sulle basi giuridiche indicate:",
    "s3_li1": "<b>Esecuzione del contratto:</b> creazione dell'account, accesso al servizio, gestione dell'abbonamento",
    "s3_li2": "<b>Legittimo interesse:</b> miglioramento del servizio, analisi interne, prevenzione delle frodi",
    "s3_li3": "<b>Consenso:</b> newsletter e comunicazioni di marketing (revocabile in qualsiasi momento)",
    "s3_li4": "<b>Obbligo legale:</b> conservazione delle fatture, conformità fiscale",
    "s4_p1": "I dati relativi alle recensioni Google sono raccolti tramite l'API Google Business Profile dopo la sua autorizzazione. Comprendono il contenuto delle recensioni (testo, valutazione, data), il nome o pseudonimo del recensore e l'identificativo della sua struttura. Tali dati servono alla visualizzazione nella dashboard, alla generazione di suggerimenti di risposta tramite IA (vedere sezione 5), agli avvisi e al reporting.",
    "s4_p2": "<b>Proprietà dei dati:</b> I dati delle recensioni visualizzati su Google Business Profile restano di proprietà del cliente o di Google, a seconda dei casi. REPUTEXA non rivendica alcuna proprietà su tali contenuti. REPUTEXA è tuttavia autorizzata a trattarli, conservarli e utilizzarli esclusivamente nell'ambito della fornitura del servizio e delle finalità descritte nel presente documento.",
    "s5_p1": "Le recensioni raccolte sono elaborate da modelli di intelligenza artificiale (fornitori quali OpenAI, Google o equivalenti) per generare suggerimenti di risposta personalizzati, esclusivamente per conto dell'utente e nel rigoroso ambito della prestazione REPUTEXA.",
    "s5_p2": "<b>REPUTEXA non vende, condivide né monetizza i dati delle recensioni o i contenuti elaborati dall'IA</b> per finalità diverse dalla fornitura del servizio. L'IA elabora le recensioni solo per consentire al cliente di rispondere e migliorare la propria reputazione online; non viene effettuato alcun uso secondario (pubblicità mirata, rivendita di dati, profilazione da parte di terzi).",
    "s6_body": "I dati di fatturazione e pagamento sono trasmessi a <strong>Stripe</strong> (Stripe, Inc.), fornitore certificato PCI-DSS, per la gestione degli abbonamenti (piani Vision, Pulse, Zenith), la tokenizzazione delle carte e l'emissione delle fatture. I dati bancari sensibili non transitano mai sui nostri server. Informativa Stripe: <stripeLink>stripe.com/privacy</stripeLink>.",
    "s7_intro": "I suoi dati possono essere trasferiti e trattati dai responsabili elencati di seguito, esclusivamente nell'ambito della loro missione. Tali trasferimenti sono effettuati in conformità al GDPR e alle informative sulla privacy di ciascun fornitore:",
    "s7_li1": "<b>Stripe</b> – Pagamenti, fatturazione e gestione degli abbonamenti (carte, rateizzazione, crediti)",
    "s7_li2": "<b>Resend</b> – Invio di email transazionali (conferme, avvisi, notifiche sull'account)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Invio di notifiche e avvisi (recensioni negative, promemoria) quando attiva questa opzione sul suo piano",
    "s7_li4": "<b>Supabase</b> – Hosting dei dati (database, autenticazione); i dati possono essere ospitati nell'Unione europea a seconda della configurazione",
    "s7_li5": "<b>OpenAI / fornitori di IA</b> – Elaborazione delle recensioni per i suggerimenti di risposta (cfr. sezione 5)",
    "s7_li6": "<b>Google</b> – Accesso OAuth e API Google Business Profile (recensioni, schede stabilimento)",
    "s7_li7": "<b>Vercel</b> – Hosting del sito e dell'applicazione",
    "s7_footer": "Questi fornitori sono soggetti a obblighi contrattuali conformi al GDPR. Può consultare le rispettive informative sulla privacy (Stripe, Resend, Meta/WhatsApp, Supabase, ecc.) sui siti ufficiali.",
    "s8_p1": "Il sito utilizza <b>cookie tecnici strettamente necessari</b> al funzionamento del servizio:",
    "s8_li1": "<b>Sessione e autenticazione</b>: mantenimento della sessione utente e sicurezza dell'accesso",
    "s8_li2": "<b>Sicurezza Stripe</b>: cookie necessari all'elaborazione dei pagamenti e alla prevenzione delle frodi",
    "s8_p2": "Questi cookie non richiedono consenso preventivo ai sensi dell'articolo 82 della legge « Informatica e libertà » e del GDPR, purché siano strettamente necessari alla fornitura del servizio. Non viene mostrato alcun banner di consenso specifico per questi cookie tecnici.",
    "s9_p1": "I suoi dati sono conservati per la durata del suo account e successivamente per i termini legali applicabili (fatturazione: 10 anni). I dati di connessione e i log sono conservati al massimo per 12 mesi. In caso di eliminazione dell'account, i suoi dati sono cancellati o anonimizzati entro 30 giorni, salvo obblighi legali di conservazione.",
    "s10_intro": "In conformità al GDPR, lei dispone dei seguenti diritti:",
    "s10_li1": "<b>Diritto di accesso</b> e di rettifica dei suoi dati",
    "s10_li2": "<b>Diritto alla cancellazione</b> (« diritto all'oblio ») nei limiti previsti dalla legge",
    "s10_li3": "<b>Diritto alla limitazione</b> del trattamento",
    "s10_li4": "<b>Diritto alla portabilità</b> dei dati",
    "s10_li5": "<b>Diritto di opposizione</b> al trattamento, in particolare per la prospezione",
    "s10_rights": "Per esercitare questi diritti, ci contatti all'indirizzo <contactLink>contact@reputexa.fr</contactLink>. Può inoltre presentare un reclamo all'autorità di controllo (in Francia, CNIL: <cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "Adottiamo misure tecniche e organizzative adeguate (crittografia SSL, autenticazione sicura, controllo degli accessi) per proteggere i suoi dati da accessi non autorizzati, perdita o alterazione.",
    "s12_p1": "Ci riserviamo il diritto di modificare la presente informativa. Ogni modifica sostanziale sarà comunicata via email o tramite notifica nell'area clienti. La data dell'ultimo aggiornamento è indicata all'inizio del documento.",
    "s13_body": "Per qualsiasi domanda relativa alla protezione dei suoi dati: <contactLink>contact@reputexa.fr</contactLink>.",
}
