# -*- coding: utf-8 -*-
"""PublicPages.privacyRoute — Portuguese (Brazilian-style neutral)."""

PRIVACY_ROUTE = {
    "metaTitle": "Política de privacidade | REPUTEXA",
    "metaDescription": "Política de privacidade e proteção de dados pessoais da REPUTEXA. Conformidade com o RGPD, avaliações Google, pagamentos Stripe.",
    "pageTitle": "Política de privacidade",
    "intro": "Última atualização: março de 2026. Esta política descreve como a REPUTEXA recolhe, utiliza e protege os seus dados pessoais em conformidade com o Regulamento Geral sobre a Proteção de Dados (RGPD).",
    "toc1": "1. Responsável pelo tratamento",
    "toc2": "2. Dados recolhidos",
    "toc3": "3. Finalidades e bases legais",
    "toc4": "4. Avaliações Google e acesso API",
    "toc5": "5. Tratamento por inteligência artificial",
    "toc6": "6. Pagamentos e dados de faturação",
    "toc7": "7. Subcontratantes e transferências de dados",
    "toc8": "8. Cookies",
    "toc9": "9. Prazo de conservação",
    "toc10": "10. Os seus direitos",
    "toc11": "11. Segurança",
    "toc12": "12. Alterações",
    "toc13": "13. Contacto",
    "s1_p1": "O responsável pelo tratamento dos seus dados pessoais é a REPUTEXA, editora do site <b>reputexa.fr</b>, com sede em França.",
    "s1_p2": "Tratamos os seus dados de forma lícita, leal e transparente, em conformidade com o RGPD.",
    "s2_intro": "Recolhemos nomeadamente:",
    "s2_li1": "<b>E-mail:</b> endereço profissional para criação de conta, comunicações e autenticação",
    "s2_li2": "<b>Dados de faturação:</b> identidade, contactos e informações de pagamento transmitidas ao Stripe para gestão de subscrições e emissão de faturas",
    "s2_li3": "<b>Acesso às avaliações via API Google:</b> conteúdo das avaliações, classificações, datas e dados da sua ficha Google Business Profile (ver secção 4)",
    "s2_li4": "<b>Dados de identificação e profissionais:</b> nome, apelido, telefone, nome do estabelecimento, morada, Google Location ID",
    "s2_li5": "<b>Dados técnicos:</b> endereço IP, registos de ligação, cookies (ver secção 8)",
    "s3_intro": "Os dados são tratados para as finalidades seguintes, com base nas fundamentações jurídicas indicadas:",
    "s3_li1": "<b>Execução do contrato:</b> criação de conta, acesso ao serviço, gestão da subscrição",
    "s3_li2": "<b>Interesse legítimo:</b> melhoria do serviço, análises internas, prevenção de fraudes",
    "s3_li3": "<b>Consentimento:</b> newsletter e comunicações de marketing (revogável a qualquer momento)",
    "s3_li4": "<b>Obrigação legal:</b> conservação de faturas, conformidade fiscal",
    "s4_p1": "Os dados relativos às avaliações Google são recolhidos através da API Google Business Profile após a sua autorização. Incluem o conteúdo das avaliações (texto, classificação, data), o nome ou pseudónimo do autor e o identificador do seu estabelecimento. Estes dados servem para a apresentação no painel, para sugestões de resposta geradas por IA (ver secção 5), alertas e relatórios.",
    "s4_p2": "<b>Propriedade dos dados:</b> Os dados de avaliações apresentados no Google Business Profile permanecem propriedade do cliente ou da Google, consoante o caso. A REPUTEXA não reivindica qualquer propriedade sobre estes conteúdos. A REPUTEXA está contudo autorizada a tratá-los, armazená-los e utilizá-los estritamente no âmbito da prestação do serviço e das finalidades aqui descritas.",
    "s5_p1": "As avaliações recolhidas são tratadas por modelos de inteligência artificial (fornecedores como OpenAI, Google ou equivalentes) para gerar sugestões de resposta personalizadas, exclusivamente em nome do utilizador e no âmbito estrito da prestação REPUTEXA.",
    "s5_p2": "<b>A REPUTEXA não vende, partilha nem monetiza dados de avaliações ou conteúdos tratados por IA</b> para fins outros que não a prestação do serviço. A IA trata as avaliações apenas para permitir ao cliente responder às suas avaliações e melhorar a sua reputação online; não é efetuado qualquer uso secundário (publicidade direcionada, revenda de dados, perfis por terceiros).",
    "s6_body": "Os dados de faturação e pagamento são transmitidos à <strong>Stripe</strong> (Stripe, Inc.), prestadora certificada PCI-DSS, para o tratamento de subscrições (planos Vision, Pulse, Zenith), tokenização de cartões e emissão de faturas. Os dados bancários sensíveis nunca transitam pelos nossos servidores. Política Stripe: <stripeLink>stripe.com/privacy</stripeLink>.",
    "s7_intro": "Os seus dados podem ser transferidos e tratados pelos subcontratantes abaixo, estritamente no âmbito da sua missão. Estas transferências são efetuadas em conformidade com o RGPD e com as políticas de privacidade de cada prestador:",
    "s7_li1": "<b>Stripe</b> – Pagamentos, faturação e gestão de subscrições (cartões, rateio, créditos)",
    "s7_li2": "<b>Resend</b> – Envio de e-mails transacionais (confirmação, alertas, notificações de conta)",
    "s7_li3": "<b>WhatsApp API (Meta)</b> – Envio de notificações e alertas (avaliações negativas, lembretes) quando ativa esta opção no seu plano",
    "s7_li4": "<b>Supabase</b> – Alojamento de dados (base de dados, autenticação); os dados podem ser alojados na União Europeia consoante a configuração",
    "s7_li5": "<b>OpenAI / fornecedores de IA</b> – Tratamento de avaliações para sugestões de resposta (ver secção 5)",
    "s7_li6": "<b>Google</b> – Ligação OAuth e API Google Business Profile (avaliações, fichas de estabelecimento)",
    "s7_li7": "<b>Vercel</b> – Alojamento do site e da aplicação",
    "s7_footer": "Estes prestadores estão sujeitos a obrigações contratuais conformes ao RGPD. Pode consultar as respetivas políticas de privacidade (Stripe, Resend, Meta/WhatsApp, Supabase, etc.) nos respetivos sites oficiais.",
    "s8_p1": "O site utiliza <b>cookies técnicos estritamente necessários</b> ao funcionamento do serviço:",
    "s8_li1": "<b>Sessão e autenticação</b>: manutenção da sessão do utilizador e segurança do acesso",
    "s8_li2": "<b>Segurança Stripe</b>: cookies necessários ao tratamento de pagamentos e à prevenção de fraudes",
    "s8_p2": "Estes cookies não requerem consentimento prévio no sentido do artigo 82 da lei « Informática e liberdades » e do RGPD, desde que sejam estritamente necessários à prestação do serviço. Não é apresentado qualquer banner de consentimento específico para estes cookies técnicos.",
    "s9_p1": "Os seus dados são conservados durante a vigência da sua conta e, em seguida, durante os prazos legais aplicáveis (faturação: 10 anos). Os dados de ligação e registos são conservados no máximo 12 meses. Em caso de eliminação de conta, os seus dados são apagados ou anonimizados no prazo de 30 dias, salvo obrigação legal de conservação.",
    "s10_intro": "Em conformidade com o RGPD, dispõe dos seguintes direitos:",
    "s10_li1": "<b>Direito de acesso</b> e de retificação dos seus dados",
    "s10_li2": "<b>Direito ao apagamento</b> (« direito a ser esquecido ») nos limites previstos na lei",
    "s10_li3": "<b>Direito à limitação</b> do tratamento",
    "s10_li4": "<b>Direito à portabilidade</b> dos dados",
    "s10_li5": "<b>Direito de oposição</b> ao tratamento, nomeadamente para prospeção",
    "s10_rights": "Para exercer estes direitos, contacte-nos em <contactLink>contact@reputexa.fr</contactLink>. Também pode apresentar uma reclamação à autoridade de controlo (em França, a CNIL: <cnilLink>cnil.fr</cnilLink>).",
    "s11_p1": "Implementamos medidas técnicas e organizacionais adequadas (encriptação SSL, autenticação segura, controlo de acessos) para proteger os seus dados contra acessos não autorizados, perda ou alteração.",
    "s12_p1": "Reservamo-nos o direito de modificar esta política. Qualquer alteração significativa será comunicada por e-mail ou através de uma notificação na sua área de cliente. A data da última atualização consta no início do documento.",
    "s13_body": "Para qualquer questão relativa à proteção dos seus dados: <contactLink>contact@reputexa.fr</contactLink>.",
}
