/** Colonnes `profiles` lues/écrites pour la fidélité merchant (éviter la dérive entre routes). */
export const BANANO_PROFILE_LOYALTY_COLUMNS =
  [
    'banano_loyalty_mode',
    'banano_loyalty_threshold',
    'banano_loyalty_reward_text',
    'banano_loyalty_points_per_visit',
    'banano_loyalty_points_per_euro',
    'banano_loyalty_stamps_per_visit',
    'banano_loyalty_stamps_per_euro',
    'banano_loyalty_bonus_enabled',
    'banano_loyalty_bonus_start_date',
    'banano_loyalty_bonus_end_date',
    'banano_loyalty_bonus_points_extra',
    'banano_loyalty_bonus_stamps_extra',
    'banano_loyalty_bonus_points_per_euro',
    'banano_loyalty_bonus_stamps_per_euro',
    'banano_loyalty_voucher_reward_kind',
    'banano_loyalty_voucher_reward_percent',
    'banano_loyalty_voucher_reward_euro_cents',
    'banano_loyalty_voucher_validity_days',
    'banano_loyalty_voucher_whatsapp_enabled',
    'banano_loyalty_threshold_stamps',
    'banano_loyalty_reward_text_stamps',
    'banano_loyalty_voucher_stamps_reward_kind',
    'banano_loyalty_voucher_stamps_reward_percent',
    'banano_loyalty_voucher_stamps_reward_euro_cents',
    'banano_loyalty_voucher_stamps_validity_days',
    'banano_loyalty_voucher_stamps_whatsapp_enabled',
    'banano_staff_allowance_enabled',
    'banano_staff_allowance_monthly_euro_cents',
    'banano_staff_allowance_validity_days',
    'banano_pilotage_ingest_secret',
  ].join(', ');
